# Generated by Django 3.0.5 on 2020-05-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address2',
            field=models.TextField(default=''),
        ),
    ]
