# Generated by Django 3.0.6 on 2020-05-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_timestamp'),
        ('orders', '0010_auto_20200508_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
